osx_image: xcode6.4
language: objective-c
xcode_project: ZipUtilities.xcodeproj
matrix:
  include:
    - xcode_scheme: ZipUtilities
      xcode_sdk: iphonesimulator
    - xcode_scheme: ZipUtilities Framework
      xcode_sdk: iphonesimulator
    - xcode_scheme: ZipUtilities OSX Framework
